unit:
  image: golang:1.10
  stage: test
  before_script:
    - curl https://raw.githubusercontent.com/golang/dep/master/install.sh | sh
    - mkdir -p /go/src/gitlab.com/8Mobius8 /go/src/_/builds
    - cp -r $CI_PROJECT_DIR /go/src/gitlab.com/8Mobius8/go-habits
    - ln -s /go/src/gitlab.com/8Mobius8 /go/src/_/builds/8Mobius8
    - cd /go/src/gitlab.com/8Mobius8/go-habits
    - make deps
  script:
    - make test-unit

integration:
  stage: test
  services:
    - docker:dind
  image: docker
  before_script:
    - docker info
    - apk add --no-cache py-pip make
    - pip install docker-compose
  script:
    - make test-integration
    
