image: registry.gitlab.com/8mobius8/go-habits/tester

docker-images:
  image: docker
  stage: build
  before_script:
    - docker info
    - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN $CI_REGISTRY
    - apk add --no-cache make
  script:
    - make build-images push=true
  services:
    - docker:dind

build:
  stage: build
  script:
    - make

unit-tests:
  stage: test
  script:
    - make test-unit

integration-tests:
  image: docker
  stage: build
  before_script:
    - docker info
    - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN $CI_REGISTRY
    - apk add --no-cache make py-pip python-dev libffi-dev openssl-dev gcc libc-dev make
    - pip install docker-compose
    - docker-compose --version
  stage: test
  script:
    - docker-compose run -w "/go/src/github.com/8Mobius8/go-habits" integration
  services: 
    - docker:dind
    
coverage:
  stage: test
  script:
    - make coverage

code_climate:
  stage: test
  script:
    - make code-climate

lint_code:
  stage: test
  script:
    - make lint