build-images:
  image: docker
  stage: build
  services:
    - docker:dind
  before_script:
    - docker info
    - apk add --no-cache py-pip make
    - pip install docker-compose
  script:
    - docker login $CI_REGISTRY -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD
    - make build-images push=true

unit-tests:
  image: docker
  stage: test
  services:
    - docker:dind
  before_script:
    - docker info
    - apk add --no-cache py-pip make
    - pip install docker-compose
  script:
    - docker-compose run -e CC_TEST_REPORTER_ID=$CC_TEST_REPORTER_ID -e ccreporter=true unit

integration-tests:
  image: docker
  stage: test
  services:
    - docker:dind
  before_script:
    - docker info
    - apk add --no-cache py-pip make
    - pip install docker-compose
  script:
    - docker-compose run integration
    
