version: "3"

services:
  tests:
    build:
      context: .
      dockerfile: _dockerfiles/go-habits-tester
    image: registry.gitlab.com/8mobius8/go-habits/tester:${CI_COMMIT_SHA}

  unit:
    image: registry.gitlab.com/8mobius8/go-habits/tester:${CI_COMMIT_SHA}
    command: ["make", "test-unit"]

  integration:
    image: registry.gitlab.com/8mobius8/go-habits/tester:${CI_COMMIT_SHA}
    command: ["make", "test-integration"]
    environment:
      SERVER: http://habitica:3000/api
    links:
      - habitica:habitica
    depends_on:
      - habitica

  habitica:
    build: 
      context: .
      dockerfile: _dockerfiles/habitica
    image: registry.gitlab.com/8mobius8/go-habits/api
    ports:
      - "3000:3000"
    environment:
      NODE_DB_URI: mongodb://mongo/habitrpg
    links:
      - mongo:mongo
    privileged: true

  mongo:
    image: mongo:3.4
    ports:
      - "27017:27017"
