version: "3"

services:
  unit:
    image: registry.gitlab.com/8mobius8/go-habits/tester
    command: ["make", "test-unit"]
    volumes:
      - .:/go/src/github.com/8Mobius8/go-habits

  integration:
    image: registry.gitlab.com/8mobius8/go-habits/tester
    command: ["make", "test-integration"]
    volumes:
      - .:/go/src/github.com/8Mobius8/go-habits
    environment:
      SERVER: http://habitica:3000/api
    links:
      - habitica:habitica
    depends_on:
      - habitica

  habitica:
    image: registry.gitlab.com/8mobius8/go-habits/api
    ports:
      - "3000:3000"
    environment:
      NODE_DB_URI: mongodb://mongo/habitrpg
    links:
      - mongo:mongo
    privileged: true

  mongo:
    image: mongo:3.4
    ports:
      - "27017:27017"
