version: "3"

services:
  unit:
    image: registry.gitlab.com/8mobius8/go-habits/tester
    command: ["make", "test-unit"]
    volumes:
      - .:/src

  integration:
    image: registry.gitlab.com/8mobius8/go-habits/tester
    command: ["make", "test-integration"]
    volumes:
      - .:/src
    environment:
      SERVER: http://habitica:3000/api
    links:
      - habitica:habitica
    depends_on:
      - habitica

  habitica:
    image: registry.gitlab.com/8mobius8/go-habits/api
    ports:
      - 3000:3000
    environment:
      NODE_DB_URI: mongodb://mongo/habitrpg
    links:
      - mongo:mongo
    privileged: true

  habitica-web:
    image: registry.gitlab.com/8mobius8/go-habits/api
    command: npm run client:dev
    ports:
      - 8080:8080
    links:
      - habitica:localhost

  mongo:
    image: mongo:3.4
    ports:
      - "27017:27017"
