version: "3"

services:
  integration:
    build: 
      context: .
      dockerfile: integration/Dockerfile
    environment:
      SERVER: http://habitica:3000/api
    links:
      - habitica:habitica
    depends_on:
      - habitica

  habitica:
    build:
      context: .
      dockerfile: integration/Dockerfile-habitica
    ports:
      - "3000:3000"
    environment:
      NODE_DB_URI: mongodb://mongo/habitrpg
    links:
      - mongo:mongo
    privileged: true

  mongo:
    image: mongo:3.4
    ports:
      - "27017:27017"
